name: Move Closed Issues Test

on:
  workflow_dispatch:
    branches: [ gh-pages-testing ]
  issues:
    types:
      - closed
jobs:
  move-closed-issue-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sort Closed Issues by Label
        uses: actions/github-script@v7
        id: sort-closed-issues-test
        with:
          script: |
            const script = require('./github-actions/move-closed-issues/sort-closed-issues-test.js')
            const sortIssues = script({context})
            return sortIssues
          result-encoding: string
